"""
Starburst last-refresh report
-----------------------------
Queries Starburst (Trino) for the last refresh time of each configured
object, builds an HTML table, flags anything stale, and emails it.

Supported "how do we know it refreshed" methods (per object, in config.yaml):
  - materialized_view : system.metadata.materialized_views.last_fresh_time
  - iceberg           : max(committed_at) from "<table>$snapshots"
  - delta             : max(timestamp)    from "<table>$history"
  - column            : max(<column>)     from the table itself (e.g. load_ts)
  - query             : any custom SQL returning one timestamp

Install:  pip install trino pyyaml
Run:      python starburst_refresh_report.py --config config.yaml
"""

import argparse
import os
import smtplib
import ssl
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import trino
import yaml


# ---------- Starburst connection ----------

def connect(cfg):
    sb = cfg["starburst"]
    password = os.environ.get(sb.get("password_env", "STARBURST_PASSWORD"))
    auth = trino.auth.BasicAuthentication(sb["user"], password) if password else None
    return trino.dbapi.connect(
        host=sb["host"],
        port=sb.get("port", 443),
        user=sb["user"],
        http_scheme=sb.get("http_scheme", "https"),
        auth=auth,
        catalog=sb.get("catalog"),
        schema=sb.get("schema"),
        verify=sb.get("verify_ssl", True),
    )


def build_sql(obj):
    method = obj["method"]
    cat, sch, tbl = obj.get("catalog"), obj.get("schema"), obj.get("table")
    if method == "materialized_view":
        return (
            "SELECT last_fresh_time FROM system.metadata.materialized_views "
            f"WHERE catalog_name = '{cat}' AND schema_name = '{sch}' AND name = '{tbl}'"
        )
    if method == "iceberg":
        return f'SELECT max(committed_at) FROM {cat}.{sch}."{tbl}$snapshots"'
    if method == "delta":
        return f'SELECT max("timestamp") FROM {cat}.{sch}."{tbl}$history"'
    if method == "column":
        return f'SELECT max({obj["column"]}) FROM {cat}.{sch}.{tbl}'
    if method == "query":
        return obj["sql"]
    raise ValueError(f"Unknown method: {method}")


def fetch_refresh_times(conn, objects):
    rows = []
    cur = conn.cursor()
    now = datetime.now(timezone.utc)
    for obj in objects:
        name = obj.get("label") or f'{obj.get("catalog")}.{obj.get("schema")}.{obj.get("table")}'
        max_age_h = obj.get("max_age_hours", 24)
        try:
            cur.execute(build_sql(obj))
            result = cur.fetchone()
            ts = result[0] if result else None
            if isinstance(ts, datetime) and ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            if ts is None:
                rows.append((name, None, None, "NO DATA"))
                continue
            age_h = (now - ts).total_seconds() / 3600
            status = "OK" if age_h <= max_age_h else "STALE"
            rows.append((name, ts, age_h, status))
        except Exception as e:  # keep going; report the failure in the mail
            rows.append((name, None, None, f"ERROR: {str(e)[:120]}"))
    return rows


# ---------- Email ----------

def to_local(ts, tz_name):
    try:
        from zoneinfo import ZoneInfo
        return ts.astimezone(ZoneInfo(tz_name))
    except Exception:
        return ts


def render_html(rows, tz_name):
    colors = {"OK": "#e6f4ea", "STALE": "#fde7e9", "NO DATA": "#fff4e5"}
    body = []
    for name, ts, age_h, status in rows:
        bg = colors.get(status, "#fde7e9")
        ts_txt = to_local(ts, tz_name).strftime("%Y-%m-%d %H:%M %Z") if ts else "-"
        age_txt = f"{age_h:.1f} h" if age_h is not None else "-"
        body.append(
            f'<tr style="background:{bg}"><td>{name}</td><td>{ts_txt}</td>'
            f"<td>{age_txt}</td><td><b>{status}</b></td></tr>"
        )
    issues = sum(1 for r in rows if r[3] != "OK")
    summary = (
        "All objects refreshed on time." if issues == 0
        else f"{issues} of {len(rows)} object(s) need attention."
    )
    return f"""
    <html><body style="font-family:Arial,sans-serif;font-size:13px">
      <p>Hi team,</p>
      <p>Daily Starburst refresh status — {summary}</p>
      <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse">
        <tr style="background:#333;color:#fff">
          <th>Object</th><th>Last refresh ({tz_name})</th><th>Age</th><th>Status</th>
        </tr>
        {''.join(body)}
      </table>
      <p style="color:#888">Auto-generated by starburst_refresh_report.py</p>
    </body></html>
    """, issues


def send_mail(cfg, html, issues):
    m = cfg["email"]
    today = datetime.now().strftime("%d-%b-%Y")
    prefix = "[ACTION NEEDED] " if issues else ""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f'{prefix}{m.get("subject", "Starburst Last Refresh Report")} - {today}'
    msg["From"] = m["from"]
    msg["To"] = ", ".join(m["to"])
    if m.get("cc"):
        msg["Cc"] = ", ".join(m["cc"])
    msg.attach(MIMEText(html, "html"))

    recipients = m["to"] + m.get("cc", [])
    smtp_pass = os.environ.get(m.get("password_env", "SMTP_PASSWORD"))
    with smtplib.SMTP(m["smtp_host"], m.get("smtp_port", 587)) as s:
        if m.get("starttls", True):
            s.starttls(context=ssl.create_default_context())
        if m.get("smtp_user"):
            s.login(m["smtp_user"], smtp_pass)
        s.sendmail(m["from"], recipients, msg.as_string())


# ---------- Main ----------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="config.yaml")
    ap.add_argument("--dry-run", action="store_true", help="Write HTML to file, don't send")
    args = ap.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    conn = connect(cfg)
    rows = fetch_refresh_times(conn, cfg["objects"])
    html, issues = render_html(rows, cfg.get("timezone", "Asia/Kolkata"))

    if args.dry_run:
        with open("refresh_report_preview.html", "w") as f:
            f.write(html)
        print("Preview written to refresh_report_preview.html")
    else:
        send_mail(cfg, html, issues)
        print(f"Report sent. {issues} issue(s).")


if __name__ == "__main__":
    main()
